plugins:
  - remark-preset-lint-consistent
  - remark-preset-lint-markdown-style-guide
  - remark-preset-lint-recommended
  # Customized Settings
  - ["remark-lint-list-item-indent", space]
  - ["remark-lint-maximum-line-length", 100]
