plugins:
    - remark-preset-lint-consistent
    - remark-preset-lint-markdown-style-guide
    - remark-preset-lint-recommended
    - remark-lint-maximum-line-length: 100
    - remark-lint-list-item-indent: space
