plugins:
    - remark-preset-lint-consistent
    - remark-preset-lint-markdown-style-guide
    - remark-preset-lint-recommended

    # Paragraphs need to work seamlessly, this is for documentation. 
    - ["remark-lint-maximum-line-length",false]
    - ["remark-lint-list-item-indent", "space"]
